config/routes.rb
Rails.application.routes.draw do
  get 'weekly_plans/index'
  get 'weekly_plans/show'
  get 'weekly_plans/new'
  root 'recipes#index'
  devise_for :users
  resources :users, only: [:show]
  resources :recipes, only: [:index, :show, :new, :create]
  resources :weekly_plans, only: [:index, :show, :new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :weekly_plan
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :ingredients, inverse_of: :recipe
  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
  has_many :plans
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes
  has_many :weekly_plans
end

app/models/weekly_plan.rb
# frozen_string_literal: true

class WeeklyPlan < ApplicationRecord
  has_many :plans
  belongs_to :user
  accepts_nested_attributes_for :plans, reject_if: :all_blank, allow_destroy: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
    @recipe.ingredients.build
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    @recipe.save
    redirect_to new_recipe_path
  end

  private
    def recipe_params
      params.require(:recipe).
        permit(:name, ingredients_attributes: [:id, :name, :amount, :cut_style, :_destroy])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def show
  end
end

app/controllers/weekly_plans_controller.rb
# frozen_string_literal: true

class WeeklyPlansController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def index
    @weekly_plans = WeeklyPlan.all
  end

  def show
    @weekly_plan = WeeklyPlan.find_by(id: params[:id])
  end

  def new
    user = User.find(current_user.id)
    @weekly_plan = user.weekly_plans.build
    7.times { @weekly_plan.plans.build }
  end

  def create
    @weekly_plan = WeeklyPlan.new(weekly_plan_params)
    @weekly_plan.user_id = current_user.id
    @weekly_plan.save
    redirect_to weekly_plans_path
  end

  private

  def weekly_plan_params
    params.require(:weekly_plan).permit(:name, plans_attributes: %i[id recipe_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weekly_plans_helper.rb
# frozen_string_literal: true

module WeeklyPlansHelper
  def organize_ingredients(weekly_plan_id)
    ingredients = WeeklyPlan.find(weekly_plan_id).plans.map(&:recipe).map(&:ingredients).flatten
    grouped = ingredients.group_by { |i| [i.name, i.cut_style] }.values
    grouped.each do |g|
      next unless g.length > 1

      total_amount = g.map(&:amount).sum
      g.uniq!
      g.first[:amount] = total_amount
    end
    grouped.flatten
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Precook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <%= link_to 'Precook', root_path, class: 'navbar-item' %>
        </div>

        <div class="navbar-menu">
          <div class="navbar-start">
            <%= link_to 'レシピ一覧', recipes_path, class: 'navbar-item' %>
            <%= link_to '週間プラン一覧', weekly_plans_index_path, class: 'navbar-item' %>
          </div>
        </div>

        <div class="navbar-end">
            <div class="navbar-item">
              <div class="buttons">
                <% if user_signed_in? %>
                  <%= link_to 'レシピ投稿', new_recipe_path, class: 'button is-primary' %>
                  <%= link_to '週間プラン作成', weekly_plans_new_path, class: 'button is-primary' %>
                  <%= link_to 'ログアウト', destroy_user_session_path, class: 'button is-light', method: :delete %>
                <% else %>
                  <%= link_to 'サインアップ', new_user_registration_path, class: 'button is-primary' %>
                  <%= link_to 'ログイン', new_user_session_path, class: 'button is-light' %>
                <% end %>
              </div>
            </div>
        </div>
      </nav>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/_ingredient_fields.html.erb
<div class="nested-fields field is-horizontal">
  <div class="field-label">
    <%= f.label :name, '材料', class: 'label' %>
  </div>
  <div class="field-body">
    <div class="field">
      <div class="control">
        <%= f.text_field :name, class: 'input', placeholder: '材料名' %>
        </div>
    </div>
    <div class="field">
      <div class="control">
        <%= f.number_field :amount, class: 'input', placeholder: '分量 [g]' %>
      </div>
    </div>
    <div class="field">
      <div class="control">
        <%= f.text_field :cut_style, class: 'input', placeholder: '切り方' %>
      </div>
    </div>
    <div class="field">
      <div class="links control">
        <%= link_to_remove_association '材料削除', f , class: 'button'%>
      </div>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">レシピ一覧</h1>
    <div class="columns is-desktop">
        <% @recipes.each do |recipe| %>
          <div class="column">
            <div class="card">
              <div class="card-image">
                <figure class="image is-4by3">
                  <img src="https://bulma.io/images/placeholders/1280x960.png" alt="Placeholder image">
                </figure>
              </div>
              <div class="card-content">
                <div class="media">
                  <div class="media-left">
                    <figure class="image is-48x48">
                      <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
                    </figure>
                  </div>
                  <div class="media-content">
                    <p>
                      <%= link_to recipe.name, recipe_path(recipe.id), class: 'title is-4' %>
                    </p>
                    <p class="subtitle is-6">@<%= recipe.user.name %></p>
                  </div>
                </div>

                <div class="content">
                  TextText...
                </div>
              </div>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</section>

app/views/recipes/new.html.erb
<h1 class="title">レシピ投稿</h1>

<%= form_for @recipe do |f| %>
  <div class="columns">
    <div class="column is-half">
      <div class="field is-horizontal is-half">
        <div class="field-label is-normal">
          <%= f.label :name, 'レシピ名', class: 'label' %>
        </div>
        <div class="field-body">
          <div class="field">
            <div class="control">
              <%= f.text_field :name, class: 'input' %>
            </div>
          </div>
        </div>

        
      </div>
      <div id="ingredients">
        <%= f.fields_for :ingredients do |ingredient| %>
          <%= render 'ingredient_fields', :f => ingredient %>
        <% end %>
      </div>
      <div class="field is-horizontal">
        <div class="field">
          <div class="control">
            <div class="links">
              <%= link_to_add_association '材料を追加', f, :ingredients,
                class: 'button',
                data: {
                  association_insertion_node: '#ingredients',
                  association_insertion_method: 'append'
                }
              %>
            </div>
          </div>
        </div>
      </div>
      <div class="field is-horizontal">
        <div class="field">
          <div class="control">
            <%= f.submit 'Submit', class: 'button is-primary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/recipes/show.html.erb
<h1 class="title"><%= @recipe.name %></h1>
<h2 class="subtitle">@<%= @recipe.user.name %></h2>

  <table class="table">
    <thead>
      <tr>
        <th>材料名</th>
        <th>分量 [g]</th>
        <th>切り方</th>
      </tr>
    </thead>
    <tbody>
      <% @recipe.ingredients.each do |ingredient| %>
        <tr>
          <td><%= ingredient.name %></td>
          <td><%= ingredient.amount %></td>
          <td><%= ingredient.cut_style %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/weekly_plans/index.html.erb
<h1 class="title">週間プラン一覧</h1>

<div class="columns">
  <% @weekly_plans.each do |wp| %>
    <div class="column is-3">
      <div class="box">
        <p>
          <%= link_to wp.name, weekly_plan_path(wp.id), class: 'title' %>
        </p>
        <p class="subtitle">
          @<%= wp.user.name %>
        </p>

        <% wp.plans.each_with_index do |p, day| %>
          <p><%= "#{day+1}日目：#{p.recipe.name}" %></p>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/weekly_plans/new.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">週間プラン</h1>

    <div class="container">
      <%= form_for @weekly_plan do |f| %>
        <div class="field is-horizontal">
          <div class="field-label is-normal">
            <%= f.label :name, 'プラン名', class: 'label' %>
          </div>
          <div class="field-body">
            <div class="field">
              <div class="control">
                <%= f.text_field :name, class: 'input' %>
              </div>
            </div>
          </div>
        </div>

        <%= f.fields_for :plans do |p| %>
          <div class="field is-horizontal">
            <div class="field-label is-normal">
              <%= p.label :recipe, "#{p.index + 1}日目のレシピ", class: 'label' %>
            </div>
            <div class="field-body">
              <div class="field">
                <div class="select">
                  <%= p.collection_select :recipe_id, Recipe.all, :id, :name %>
                </div>
              </div>
            </div>
          </div>
        <% end %>

        <div class="field is-horizontal">
          <div class="field-label"></div>
          <div class="field-body">
            <div class="field">
              <div class="control">
                <%= f.submit '保存', class: 'button is-primary' %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/weekly_plans/show.html.erb
<div class="box">
  <h1 class="title"><%= @weekly_plan.name %></h1>
  <h2 class="subtitle">@<%= @weekly_plan.user.name %></h2>

  <% @weekly_plan.plans.each_with_index do |p, day| %>
    <p><%= "#{day+1}日目：#{p.recipe.name}" %></p>
  <% end %>

  <table class="table">
    <thead>
      <tr>
        <th>材料名</th>
        <th>切り方</th>
        <th>分量</th>
      </tr>
    </thead>
    <tbody>
      <% organize_ingredients(@weekly_plan.id).each do |i| %>
        <tr>
          <td><%= i.name %></td>
          <td><%= i.cut_style %></td>
          <td><%= i.amount %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>